### PR TITLE
Colorized console fix in Windows

### PR DESCRIPTION
**Pull request by ronindev**
Added few changes for proper work from windows machine

### CODE REVIEW

**Comment by mdevan** [comment]
Looks good. Will merge soon.

**Comment by mdevan** [comment]
@ronindev Could you please resubmit after merging in the latest changes? The repo is now `go get`-table.

Also, if you guys are good with windows, any suggestions/patches on how to read the password without echo would be welcome.

**Comment by ronindev** [comment]
@mdevan Please take a look. Did I do it right?

**Comment by mdevan** [comment]
Applied, thanks!

**Pull request closed without merging**
